#!/usr/bin/env bash
echo "   ___  ___    ________________  _____ 
  / _ \/ _ )  / __/ __/_  __/ / / / _ \\
 / // / _  | _\ \/ _/  / / / /_/ / ___/
/____/____/ /___/___/ /_/  \____/_/    
                                       
v1.0.0-Rayne"
current_path=$( pwd )
echo ""
echo -n "Is this for first time setup? y/n :"
read -r setup
if [ $setup == y ] || [ $setup == yes ]; then
	echo -e "This is for first time setup.\nUse ddevstart after this setup"
	ddev config
	ddev start
	echo -e "Enter name of the file you want to use.\nMake sure the database file is in the same directory\n(It's much easier)"
	echo -n "Database File:"
	read -r database
	mv $database $PWD/currentdb.sql.gz
	ddev import-db --src=currentdb.sql.gz
	ddev drush cr
	ddev drush en stage_file_proxy -y
	ddev drush config-set stage_file_proxy.settings origin "https://www.njcu.edu/"
	ddev drush cr
	echo -e "YOU'RE ALL SET! See your local information below."
	ddev status

else
	rm current.sql.gz
	echo -e "Enter name of the file you want to use.\nMake sure the database file is in the same directory\n(It's much easier)"
	echo -n "Database File:"
	read -r database
	mv "$database" "$current_path/currentdb.sql.gz"
	ddev import-db --src=currentdb.sql.gz
	ddev drush cr
fi
